### ISSUE TITLE
Options / Preflight request returns 404 even if CORS is configured to allow requests from subdomains using wildcard (*)

### ISSUE THREAD

**Issue by AkshayMorey-BB** [Azure/azure-functions-on-container-apps#64]
**Which trigger/binding are you using?**
HttpTrigger

**Which language are you using?**
C#

**Expected behavior**
Options/Preflight request should succeed for subdomains added with wildcard (*)

**Actual behavior**
Options/Preflight requests returns 404 if CORS is configured with wildcard (*) subdomain. The request succeeds if complete domain name is added.

**Screenshots**
![failed_config](https://github.com/Azure/azure-functions-on-container-apps/assets/123961043/129156d5-4b47-422e-85ca-91c0a2d90343)
![failed_req](https://github.com/Azure/azure-functions-on-container-apps/assets/123961043/71ac5069-8301-497b-8c44-29cb976e4ba2)
![success_config](https://github.com/Azure/azure-functions-on-container-apps/assets/123961043/d0d561ce-e275-4210-95b2-3661da99c5d3)
![success_req](https://github.com/Azure/azure-functions-on-container-apps/assets/123961043/23639fe9-9fcf-4247-b336-d6ee425ebdce)

**Comment by raorugan** [comment]
@AkshayMorey-BB  - can you please provide resource details like Function App name and Resource id

**Comment by AkshayMorey-BB** [comment]
@raorugan This can be replicated on azure portal by creating a function with dotnet8-quickstart-demo image as well. The Test/Run for HttpExample function succeeds if "https://portal.azure.com" is added to CORS allowed origins, but fails - with the options requests returning 404, if allowed origin is changed to "https://*.azure.com".

**Comment by v-shenoy** [comment]
This is expected behavior. From the container apps documentation ([link](https://learn.microsoft.com/en-us/azure/container-apps/cors?tabs=arm&pivots=azure-portal)) you can see that the `allowedOrigins` property maps to the [Access-Control-Allow-Origin](https://developer.mozilla.org/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) property of the CORS spec.

Valid values for this property are:
* - wildcard for matching all domains
null - for matching none
<origin> - for matching specific domains
