### ISSUE TITLE
Creating Function as Azure Container App creates new Resource Group and I cannot control the name of it

### ISSUE THREAD

**Issue by iulian-popescu** [Azure/azure-functions-on-container-apps#81]
A new resourcegroup with the following name is created: {MANAGED_ENV_NAME}_FunctionApp_{RANDOM_STRING}
I would like to be able to control the name of the resourcegroup, so that I can have a policy regarding resource group naming.

Is there a property that I can set on either container app env or functionApp, similar to the infrastructureResourceGroup property from container app env?

**Comment by v-shenoy** [comment]
Unfortunately, there is no way to control the predetermined name of the managed resource group. Can you share some more details on the policy so that we can potentially provide a workaround?

**Comment by raorugan** [comment]
@iulian-popescu  - this is a system managed resource and not a user controlled/managed resource group. For more details refer here - https://learn.microsoft.com/en-us/azure/azure-functions/functions-container-apps-hosting#managed-resource-groups. However would like to know about your org level naming policy

**Comment by francovanzyl96** [comment]
Hi @v-shenoy,

I am running into a similar policy issue with regards to the managed resource group.

The policy requires a certain set of tags to be set on all resource groups and it would be ok to exempt this managed resource group, however it is not possible to know the name that the managed resource will get in order to exempt it.

2 possible solutions as I see it, 1. make the managed resource group name configurable, 2. inherit the tags applied to the function app resource on the managed resource group

**Comment by v-shenoy** [comment]
The tags set on the first function app created in the container apps environment are inherited by the managed resource group. You can use this to set tags as per your policy.
