### ISSUE TITLE
Function is scaled down to 0 despite cron expression every 5min

### ISSUE THREAD

**Issue by ogix** [Azure/azure-functions-on-container-apps#83]
I have function app with multiple timer-triggered functions. One of them has cron expression that runs every 5 minutes (0 */5 * * * *). Despite that I noticed that function app scaled down to 0 for the whole time until another timer triggered "wake up".

Notice the gap where red line is:
![Image](https://github.com/user-attachments/assets/b98ee037-af80-4c20-bdc1-e2f93c2471e3)

I can set min replica to 1 but still this is a major issue that should be addressed. And I am going to change cron expression to run every hour - so scaling to 0 will be beneficial.

function name: func-we-tst-westeu-2

**Comment by v-shenoy** [comment]
Will investigate this and get back to you.

**Comment by ogix** [comment]
Any news?

**Comment by krishnajaju** [comment]
Hi @ogix, thanks for your patience. We have reviewed your issue, and it seems the timer trigger function was not successfully loaded due to configuration issues in the Function App during the incident period. Here's what we have found so far. Please feel free to correct us if we have misunderstood anything:
1. 2024-10-09T10:45:00: Timer trigger in the Function App worked as expected, as seen from the image shared above.
2. 2024-10-09T10:45:36: Function App was **deleted** by the customer.
3. 2024-10-09T13:29:21: Attempt to create the Function App with the same name failed due to image authorization issues.
4. 2024-10-10T12:20:33: Function App was **recreated** successfully with successfully with the same name.
5. 2024-10-10T12:46:21: Function App is running; however, only the HTTP trigger is loaded successfully. No other function triggers were found running. We see some exceptions around missing parameter `connectionString`. _[Function logs can be found in Application Insights configured with the Function App - ([reference](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2))].
6. 2024-10-10T12:47:42: Function App was **stopped** by the customer.
7. 2024-10-10T14:07:33: Customer performed management operations on Function App, such as updating app settings.
8. 2024-10-11T05:09:43: Function App was **started** by the customer.
9. 2024-10-11T05:09:43: Timer trigger function in the Function App is running as expected, as seen from the image shared above.

Hope this clarifies things. Let us know if there are any other points that need attention.

**Comment by krishnajaju** [comment]
Hi @ogix, we have shared the investigation details and found everything is working fine on the scaling part. Since we haven't received any further response, we will close this ticket. Please feel free to reopen it if needed.
